#!/usr/bin/env bash
# world wide web

function dign () {
    text=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
    echo "The subdomain $2 is a A record and points to $text"
}
if [[ $# = 1 ]]; then
    dign "$1" "www"
    dign "$1" "lb-01"
    dign "$1" "web-01"
    dign "$1" "web-02"
elif [[ $# = 2 ]]; then
    dign "$1" "$2"
fi