#!/usr/bin/env bash
# firewall to block all incoming traffic

apt-get update
apt-get install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow http
ufw allow https
ufw enable
